### ISSUE TITLE
Interface.cpp for Mac OS compilation

### ISSUE THREAD

**Issue by jim-normand** [g-tollini/P1RV-fusee#1]
In roder to be able to compile on Mac as well please modify the header as is
`#ifndef __APPLE__
   #include "GL/freeglut.h"
   #include "GL/glut.h"
   #include "GL/gl.h"
#else
   #include "OPENGL/gl.h"
   #include "GLUT/glut.h"
#endif`

**Comment by g-tollini** [comment]
Thank you
